name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease
  
      - name: Extract version and rename APK
        run: |
          VERSION=$(grep "versionName =" app/build.gradle.kts | awk -F '"' '{print $2}')
          mv app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/ViPER4Android-$VERSION-unsigned.apk
          
      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
